# Export all route modules
from . import (
    auth,
    accounts,
    contacts,
    leads,
    opportunities,
    cases,
    dashboard,
    activities,
    logs,
    service,
    platform_events,
    sap_integration,
    mulesoft,
    mulesoft_integration,
    client_users,
    client_auth,
)

__all__ = [
    'auth',
    'accounts',
    'contacts',
    'leads',
    'opportunities',
    'cases',
    'dashboard',
    'activities',
    'logs',
    'service',
    'platform_events',
    'sap_integration',
    'mulesoft',
    'mulesoft_integration',
    'client_users',
    'client_auth',
]
